name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git push https://hxriharan:$HF_TOKEN@huggingface.co/spaces/hxriharan/Retinex_Project main
          # If GH default branch is master, use:
          # git push https://hxriharan:$HF_TOKEN@huggingface.co/spaces/hxriharan/Retinex_Project master:main 